spring.application.name=urbanpulse-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/urbanpulse
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del backend
server.port=8080